version: '3'

services:

  app:
    build: .
    image: file-storage:latest
    container_name: app
    env_file:
      - ./deploy/.env.prod
    ports:
      - 8080:8080
    networks:
      - app

networks:
  app:
